services:
  - type: web
    name: powergy-analytics
    env: docker
    plan: starter
    healthCheckPath: /api/today
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: KYOS_URL
        value: https://gas.kyos.com/
      - key: APP_BASE_URL
        value: https://spravy.powergy.sk

  - type: cron
    name: powergy-scraper-daily
    env: docker
    schedule: "0 5 * * *"
    command: ["python","-c","from app.scraper import run_daily; run_daily()"]
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: KYOS_URL
        value: https://gas.kyos.com/
